version: "3"

services:
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL}
    ports:
      - "3000:8080"
    volumes:
      - /app/node_modules
