# fly.toml app configuration file generated for ecommerce-web on 2023-06-30T20:00:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ecommerce-web"
primary_region = "ams"

[[statics]]
  guest_path = "/app/dist"
  url_prefix = "/"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
